services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        command:
            - --enable-feature=exemplar-storage
            - --web.enable-remote-write-receiver
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - 9090:9090
    grafana:
        container_name: grafana
        image: grafana/grafana
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        volumes:
            - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
            - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
            - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
        ports:
            - 3000:3000
    tempo:
        container_name: tempo
        image: grafana/tempo
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        command: [ '-config.file=/etc/tempo.yml' ]
        volumes:
            - ./config/grafana/tempo.yml:/etc/tempo.yml:ro
            - ./tempo-data/:/tmp/tempo
        ports:
            - 3200:3200 # tempo
            - 9411:9411 # zipkin
            # - 14268:14268  # jaeger
    loki:
        container_name: loki
        image: grafana/loki
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        command: [ '-config.file=/etc/loki/local-config.yaml' ]
        ports:
            - 3100:3100
