services:
    otel-collector-debug:
        container_name: otel-collector-debug
        image: otel/opentelemetry-collector-contrib
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        command: [ '--config=/etc/otel-collector-config.yml' ]
        volumes:
            - ./config/otel/otel-collector-config.yml:/etc/otel-collector-config.yml:ro
        ports:
            - "4317:4317"   # OTLP gRPC receiver
            - "4318:4318"   # OTLP http receiver
            - "9411:9411"   # Zipkin receiver
            - "8888:8888"   # Prometheus metrics exposed by the collector
            - "8889:8889"   # Prometheus exporter metrics
