name: otel-collector-prometheus-zipkin
services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        command:
            - --enable-feature=exemplar-storage
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - 9090:9090
    zipkin:
        container_name: zipkin
        image: openzipkin/zipkin
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        ports:
            - 9412:9411
    otel-collector:
        container_name: otel-collector
        image: otel/opentelemetry-collector-contrib
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        command: [ '--config=/etc/otel-collector-config.yml' ]
        volumes:
            - ./config/otel/otel-collector-config.yml:/etc/otel-collector-config.yml:ro
        depends_on:
            - prometheus
            - zipkin
        ports:
            - "4317:4317"   # OTLP gRPC receiver
            - "4318:4318"   # OTLP http receiver
            - "9411:9411"   # Zipkin receiver
            - "8888:8888"   # Prometheus metrics exposed by the collector
            - "8889:8889"   # Prometheus exporter metrics
            - "55679:55679" # zpages extension
            - "1888:1888"   # pprof extension
            - "13133:13133" # health_check extension
