services:
    github-changelog-generator:
        container_name: github-changelog-generator
        image: springio/github-changelog-generator:0.0.9
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        environment:
            # Set credentials in an .env file
            # https://docs.docker.com/compose/environment-variables/set-environment-variables/#substitute-with-an-env-file
            - GITHUB_USERNAME=${GITHUB_USERNAME}
            - GITHUB_PASSWORD=${GITHUB_PASSWORD}
        command:
            [
                'java',
                '-jar',
                '/github-changelog-generator.jar',
                '--spring.config.location=/config/changelog-generator.yml',
                '1.11.0',
                '/generated/changelog.md'
            ]
        volumes:
            - ./config:/config
            - ./generated:/generated
