version: '3'
services:
    postgres:
        container_name: postgres
        image: postgres
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        environment:
            POSTGRES_DB: testdb
            # POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
            - ./local-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    adminer:
        container_name: adminer
        image: adminer
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        depends_on:
            - postgres
        ports:
            - 8888:8080

# credentials: postgres:password
# http://localhost:8888/?pgsql=postgres&username=postgres
